### ISSUE TITLE
Multiple token support for verifying App Tokens

### ISSUE THREAD

**Issue by Atrix1987** [google/gcm#102]
The API: https://iid.googleapis.com/iid/info takes only one token per call. Is it possible to add multiple tokens in one call ? This would reduce the number of calls we make.

**Possible solution:** POST API which takes in an array of tokens. You can limit the number of tokens to 1000 per request. If it causes delay in the response, a post back mechanism also works.

**Comment by Atrix1987** [comment]
@tjohns can you please check if this is feasible ?

**Comment by kroikie** [comment]
You can send a message with up to 1000 tokens per request by using the registration_ids field. implemented [here](https://github.com/google/gcm/blob/master/client-libraries/java/rest-client/src/com/google/android/gcm/server/Sender.java#L395).

You can find more on the using registration_ids in the [docs](https://developers.google.com/cloud-messaging/http-server-ref#downstream-http-messages-json).

**Comment by kroikie** [comment]
Sorry I did misunderstood your question. I will make a note of your request and provide any updates here.

**Comment by Atrix1987** [comment]
Can we reopen the issue until we get multiple token support :smile:

**Comment by Atrix1987** [comment]
@kroikie Can you please reopen the issue until we get multiple token support ?

**Comment by silvolu** [comment]
@Atrix1987 We'd like to keep this closed because, although it's very valuable feedback, it's not related to the content of the repo, which this issue tracker should be about.

**Comment by Atrix1987** [comment]
@silvolu can you please point me in the right direction as to where I should raise it ?
