### ISSUE TITLE
GCM for Xcode 7: Link warnings (Bitcode off)

### ISSUE THREAD

**Issue by ChuckSoper** [google/gcm#104]
We're using Xcode 7 and have set "Enable Bitcode" to No. Our project with GCM builds fine, but we're getting 14 linker warnings. The warnings say, libProtocolBuffers.a(Descriptor.pb.o)) was built for newer iOS version (8.3) than being linked (8.0).

We're using:
iOS Deployment Target: iOS 8
Base SDK: Latest iOS (iOS 9)

Is there a way to build GCM so that we don't get these warnings? Our Xcode Server sends out emails whenever we have errors or warnings. We try to maintain zero warnings. Or, is there a way to turn off these warnings?

Thanks!

Full list of warnings:

```
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(Descriptor.pb.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(ObjectivecDescriptor.pb.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBArray.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBCodedInputStream.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBDescriptor.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBUtilities.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBExtensionField.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBExtensionRegistry.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBField.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBGeneratedMessage.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBRootObject.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBCodedOutputStream.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBUnknownFieldSet.o)) was built for newer iOS version (8.3) than being linked (8.0)
Object file (/Users/chuck/myApp/iphone/Pods/GoogleInterchangeUtilities/Libraries/libProtocolBuffers.a(PBWireFormat.o)) was built for newer iOS version (8.3) than being linked (8.0)
```

**Comment by mohitsharma0690** [comment]
Here http://stackoverflow.com/questions/31843900/google-cloud-messaging-for-ios-7/31865297#31865297

There is no way to disable the warnings for now.

**Comment by ChuckSoper** [comment]
Thanks for your comment. It looks like OpenSSL-Pod fixed the same issue:
https://github.com/FredericJacobs/OpenSSL-Pod/issues/20

I believe that the fix was added to their podspec with the line shown here:
https://github.com/FredericJacobs/OpenSSL-Pod/blob/master/1.0.204.1/OpenSSL.podspec#L17

Can someone possibly confirm this (or determine how OpenSSL-Pod fixed the issue)? I'm not sure of the best way to report this issue. We're trying to get our project back to zero warnings. Thanks.

**Comment by JaxMyers** [comment]
I am having the same problem with CorePlot 2.0. Never had a problem with 1.x. If you can explain how to fix it it might help me with my project (sorry if this is off topic).

**Comment by ChuckSoper** [comment]
@JaxMyers Click on my links above. I believe that the following line needs to be added to the podspec:
MIN_SDK_VERSION_FLAG="-miphoneos-version-min=7.0"
Of course, this depends on what your minimum version is.

How do I request that GCM has this issue fixed? Do developers monitor these issues?

**Comment by mohitsharma0690** [comment]
We know that this is an issue. It will be fixed soon in the next GCM on iOS release.

**Comment by ChuckSoper** [comment]
@mohitsharma0690 Thank you. :+1:

**Comment by zanyfly** [comment]
i met the same problem

**Comment by mihahribar** [comment]
+1

**Comment by mohitsharma0690** [comment]
This should be fixed now. Can you guys do a `pod update` and see if the warnings disappear or not?

**Comment by mihahribar** [comment]
:+1: all gone!

**Comment by mohitsharma0690** [comment]
The latest pods should have no warnings as @mihahribar confirmed.

**Comment by akashgupta88** [comment]
@mohitsharma0690 Yep, all warnings gone now!

**Comment by ChenJian345** [comment]
+1
