### ISSUE TITLE
Not able to get Configuration File to set GCM for Push Notifications in my iOS app

### ISSUE THREAD

**Issue by guptameet** [google/gcm#107]
I am setting up GCM for Push Notification in my iOS app. I am following GCM Documentation to configure my app. In step 2. Get a configuration file, when I click on that blue button  

<img width="917" alt="screen shot 2015-09-24 at 5 35 05 pm" src="https://cloud.githubusercontent.com/assets/14175408/10073882/be32a9a0-62e9-11e5-9279-d45253c92c82.png">

I get a page to fill my app name and bundle ID of my iOS app. After filling the right info in the spaces, I continue and I get this error.

<img width="801" alt="screen shot 2015-09-24 at 5 41 37 pm" src="https://cloud.githubusercontent.com/assets/14175408/10073888/cf8498ee-62e9-11e5-959d-2c77ad64667f.png">

Any idea, why am I getting this error.

I am also not able to find where should I be uploading .p12 files of my APNS certificates to complete the setup.

**Comment by silvolu** [comment]
@guptameet I cannot reproduce using the exact values that you're using, are you still experiencing this? You will be able to upload the p.12 certificates after successfully creating the app.

**Comment by guptameet** [comment]
Tried just now. Still facing the same issue.

[image: Inline image 1]

Meet Gupta,
Technology Architect - iOS Dev
+91 8130724442

**Comment by silvolu** [comment]
Thanks! We are investigating the issue, I will post updates here as soon as I know more.

**Comment by silvolu** [comment]
@guptameet this should be solved, can you try again?

**Comment by guptameet** [comment]
Solved. Thanks a lot.

Meet Gupta,
Technology Architect - iOS Dev
+91 8130724442
