### ISSUE TITLE
setRegisterOnServerLifespan should check for a negative value

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#11]
```
GCMRegistrar.setRegisterOnServerLifespan() should check for a negative value 
for the lifespan.

Not a big deal, caused a problem for me when I messed up my lifespan 
calculation.


```

Original issue reported on code.google.com by `m...@indigorose.com` on 29 Oct 2012 at 8:47

**Comment by silvolu** [comment]
This feature has been deprecated in the new [Google Play Service InstanceID API](https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID)
