### ISSUE TITLE
What does the port firewall coming from GCM server?

### ISSUE THREAD

**Issue by ThanawatMas** [google/gcm#110]
I have a problem with port firewall for receiving notification from GCM server.
My private network use allowed policy firewall, so I try to config follow this link
(http://esupport.trendmicro.com/solution/en-US/1060693.aspx) .
I hope it works, but it's not.

I search in many way to solve, but I couldn’t make head or tail of it.

**Comment by ogeidix** [comment]
The GCM needs the following connections:
- port: 5228, host: mtalk.google.com
- port: 443, host: android.googleapis.com

**Comment by ThanawatMas** [comment]
Great thank, Finally I got it. > <

**Comment by ogeidix** [comment]
UPDATE: GCM is also using:
- port: 443, host: android.client.google.com

**Comment by lakshaydulani** [comment]
this is about devices receiving push notifications.. My server is blocking attempt to initiate push request to GCM server...What ip/port I should open to send push notification request to GCM?
