### ISSUE TITLE
[iOS] use notification payload does not alert usually

### ISSUE THREAD

**Issue by yutin1987** [google/gcm#112]
I sent message use notification payload,

```
{
  "collapseKey": timestamp,
  "notification": {
    "title": "GCM",
    "body": "Hello World" + index
  }
}
```

will get message on my iOS app when it is open,
after click home button it not have any alert at top,
open that app again, will get last message.

should have top alert on my iPhone, sometimes there.

Network is iPhone 4G LTE.
may do not send APNS?

https://www.youtube.com/watch?v=7c_WQh9U0EE

**Comment by mohitsharma0690** [comment]
You need to add the `priority` field to receive the messages when your app is inactive or in the background. For example

```
{
  "priority": "high", // Add this
  "notification": {
    "title": "GCM",
    "body": "Hello World" + index
  }
}
```

Also FYI  the message you send above is sent via APNS which collapses all messages. So your `collapseKey: timestamp` doesn't really have any significance.

**Comment by yutin1987** [comment]
Thanks,
it works, when add "priority": "high"
