### ISSUE TITLE
Getting error while uploading .P12 file

### ISSUE THREAD

**Issue by PRCV** [google/gcm#114]
I am facing one issue when I am trying to confiure the GCM and getting configuration file. When I am trying to upload the development certificate over the GCM portal it says "There was an unknown backend error while processing the request.Try again
![error12](https://cloud.githubusercontent.com/assets/9638830/10303086/df955680-6c2e-11e5-91ac-87750b49bd5a.JPG)
 Anyone help plz.

**Comment by PRCV** [comment]
solved.

**Comment by Renu29** [comment]
m facing the same problem, how you solved it? please help.

**Comment by GeetCD** [comment]
@PRCV can you please post how you solved it, I am facing the same issue currently

**Comment by tonholis** [comment]
Same problem here. 
@PRCV How did you solve?

**Comment by raymondjacobson** [comment]
Anything on this?

**Comment by anphanngocvn** [comment]
The same problem, how to resolve? it works with production file

**Comment by raymondjacobson** [comment]
I don't remember exactly what I did, but I got it work eventually. Had to redo the entire process. Hope that helps.
