### ISSUE TITLE
GAE XMPP support for GCM CCS

### ISSUE THREAD

**Issue by dipbhi** [google/gcm#115]
- What is the desired behavior of the feature? (Be specific!) - Make GAE XMPP API/Service compatible with GCM CCS XMPP 
  - If relevant, why are current approaches or workarounds insufficient? - Current approach/workaround is to use HTTP APIs, which are not as efficient as XMPP. Also CCS XMPP supports bi-directional communication with the client app. In case of HTTP, only downstream is supported. App server has to have a custom implementation for upstream communication.
  - If relevant, what new use cases will this feature will enable? - Bi-directional messaging with client apps via GCM CCS. A quite a few apps can leverage the robust GCM infrastructure for high performance communication with the client apps from an app hosted on the appengine

P.S.: I was referred to this repo after filing a feature request in GAE repo. https://code.google.com/p/googleappengine/issues/detail?id=12387

**Comment by murrekatt** [comment]
:+1:

**Comment by silvolu** [comment]
@dipbhi thanks for submitting your feature request; this issue tracker is mostly for bugs/feature request against the content of the repo. The best way to send feedback for the product is to use the SEND FEEDBACK link that you can find in the docs, e.g. https://developers.google.com/cloud-messaging/

**Comment by murrekatt** [comment]
@silvolu it's not easy to know what channel to use...maybe something to improve to avoid this kind of ping-pong? ;-)

**Comment by dipbhi** [comment]
@silvolu - thanks for your reply. I will try out the feedback option.

@murrekatt - GAE team closed request on me saying not their problem. GCM team closes the request saying not their code. I guess Google has become too big to be customer friendly, nothing against people replying to my requests though, I appreciate that they are sparing some time to respond.

**Comment by silvolu** [comment]
@dipbhi sorry to hear your frustration; FWIW, I didn't say that it's not our code; I just said that this is not the appropriate channel for product feedback, and pointed you to the appropriate channel.
