### ISSUE TITLE
200 Not registered error on sending group notification using GCM notification key

### ISSUE THREAD

**Issue by satyenv** [google/gcm#118]
I am trying to send gcm group notifications to android devices from my rails server. But unfortunately I can't get it to work. But if I try to send the same message to single registration id, it works fine. So i checked it with curl-

curl -vvv -X POST --header "Content-Type: application/json" --header  
"project_id: MyProjectid" --header "Authorization: key=Mykey" --data @- 
"https://android.googleapis.com/gcm/send" << EOF
{
  "to": **"Reg_id"**,
  "data": {}
}
EOF

The above gives me 200 OK. But here if I replace the Reg_id with the notification_key I get 200 NotRegistered and the message was not delivered. So I did a little more research and found out when I send a gcm message the notification_key get unregistered by itself.

Below is the simple scenario with I made this assumption - If I create a new notification_key using curl it gives me the notification_key. If I create a new key using the same notification_key_name I get notification_key already exists. But once I send a notification using same notification_key, I get 200 Not registered error. Then if I try to create a new notification_key using previous notification_key_name I get a new notification_key.

This seems very weird to me. Has anyone faced the same issue or found the solution for this?

**Comment by ogeidix** [comment]
Hi Satyen,

We had a recent issue in the send API, affecting a subset of the notification_key requests.
That issue should be fixed now.

Please try again. If the API is still not working for you please report back using:
https://support.google.com/code/contact/gcm_dev_support

Thanks,
- Diego
