### ISSUE TITLE
14 warnings: .pcm: No such file or directory

### ISSUE THREAD

**Issue by tapz** [google/gcm#121]
I'm getting 14 following kind of warnings. I have ENABLE_BITCODE = NO for the pods frameworks and for my app.

while processing /Users/tapani/projects/Company/appname-ios/appname/Pods/GoogleCloudMessaging/Libraries/libGcmLib.a(GCMAuthKeychain.o):
warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/3HURGY91WKEDV/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/tapani/projects/Company/appname-ios/appname/Pods/GoogleCloudMessaging/Libraries/libGcmLib.a(GCMAuthKeychain.o):
warning: /var/folders/f4/lg23spf10fv19twg_lmrp8zm0045gx/C/org.llvm.clang.136701/ModuleCache/3HURGY91WKEDV/Foundation-3DFYNEBRQSXST.pcm: No object file for requested architecture

**Comment by mohitsharma0690** [comment]
Umm not sure what exactly is the issue but you might want to try to the solutions in this thread https://forums.developer.apple.com/thread/17921. 

I would specifically do `GCC_PRECOMPILE_PREFIX_HEADER: NO` to see if that fixes it.

**Comment by tapz** [comment]
I added this to my podfile, but it didn't help. GCM is the only library that causes the warnings. E.g. FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit, Alamofire, Cloudinary, NewRelic, PINCache etc. compile without warnings.

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['GCC_PRECOMPILE_PREFIX_HEADER'] = 'NO'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'NO'
    end
  end
end

**Comment by tapz** [comment]
The problem with the Google library is that it's not open source and is distributes as binary. That just causes problems. So please make it open source and even better port it to Swift.

**Comment by mohitsharma0690** [comment]
What Xcode version are you using? Also are you using the GCM pod as `pod Google/CloudMessaging`? 

I'm not able to reproduce your issue.

**Comment by tapz** [comment]
Xcode 7.1 (7B91b)
pod 'Google/CloudMessaging'

**Comment by mohitsharma0690** [comment]
Still not able to reproduce your issue.

Can you try building a new sample project and just having `pod 'Google/CloudMessaging'` in your podfile and see if it still happens?

**Comment by tapz** [comment]
Does Google have a REST API for GCM, so I could make my own implementation of the library? I really don't like to use any 3rd party blackbox libraries.

**Comment by mohitsharma0690** [comment]
Not right now, the GCM server API is tied with the client API.

**Comment by vadimtrifonov** [comment]
Same issue here.

**Comment by mohitsharma0690** [comment]
@vatrif We know why the issue happens. We will fix this in the next release. For now you can actually change the `Debug Information Format` in your Build Setting to `DWARF` rather than `DWARF with dSYM`. This would disable crashalytics etc for GCM but should remove the warnings. Next release should fix this completely.

**Comment by blixt** [comment]
I'm having this issue too and I really don't want to disable Crashlytics. Is there any timeline for the next version?

**Comment by benlachman** [comment]
Same issue… lots of error messages. Also, compiling without dSYM isn't a solution. That's the way you get crash report info from every crash reporting tool out there. This has been solved for 20 days and nothing?

**Comment by bitpit** [comment]
Experiencing the same issue here, with >200 warnings caused by GCM and its friends. 
On Xcode 7.1.1 using GCM 1.1.0.

Between the api version build warning on the last release and now this, i'm starting to consider whether GCM is worth continuing to use...

**Comment by JuanjoArreola** [comment]
I have the same issue, can we expect a fix soon?

**Comment by mohitsharma0690** [comment]
Yes, anytime soon now.

**Comment by mohitsharma0690** [comment]
This should be fixed in the latest release. Please check the latest release to see if it fixes your issue.

**Comment by mohitsharma0690** [comment]
I just verified that this is fixed. I'll close this for now. Please reopen if you still see the issue.

**Comment by oded-regev** [comment]
It would be nice if Google could share their solution with the rest of the world :)
