### ISSUE TITLE
Notifications not showing up for iOS using Release build

### ISSUE THREAD

**Issue by jamesromo-wf** [google/gcm#125]
I'm having trouble receiving notifications for the iOS app, but only when the build configuration is set to Release. On Debug the notifications show up fine. The only difference that I can see on my end is that we set the sandbox flag based on if we are building a Debug build or not:

``` obj-c
- (void)requestRegistrationToken:(NSData *)deviceToken {
    // Start the GGLInstanceID shared instance with the default config and request a registration
    // token to enable reception of notifications
    BOOL useSandbox;

#ifdef DEBUG
    useSandbox = YES;
#else
    useSandbox = NO;
#endif

    GGLInstanceIDConfig *instanceIDConfig = [GGLInstanceIDConfig defaultConfig];
    instanceIDConfig.delegate = self;

    [[GGLInstanceID sharedInstance] startWithConfig:instanceIDConfig];

    self.registrationOptions = @{kGGLInstanceIDRegisterAPNSOption:deviceToken,
                                 kGGLInstanceIDAPNSServerTypeSandboxOption: @(useSandbox)};

    [[GGLInstanceID sharedInstance] tokenWithAuthorizedEntity:[WFPushNotificationManager sharedManager].gcmSenderID
                                                        scope:kGGLInstanceIDScopeGCM
                                                      options:[WFPushNotificationManager sharedManager].registrationOptions
                                                      handler:[WFPushNotificationManager sharedManager].registrationHandler];
}
```

I have tried to create a Release build with `useSandbox` set to `YES` as well without any luck. Both the development and production certificates are installed on the server.

I'm not getting any errors when it does not work and the logging is set to `kGGLInstanceIDLogLevelDebug`.

Is there something I am missing?

**Comment by mohitsharma0690** [comment]
What is the response you get back from the server? 

Please use this form https://support.google.com/code/contact/gcm_dev_support to send us the relevant info. Please do enter some registration tokens that you get back for your Release builds also the sample message that you're trying to send.

**Comment by mohitsharma0690** [comment]
Not sure what's the status with this one. I'll be closing it for lack of activity.

**Comment by ghost** [comment]
Same problem here:
https://github.com/googlesamples/google-services/issues/182#issuecomment-207059382
