### ISSUE TITLE
`sound` field not working on iOS?

### ISSUE THREAD

**Issue by blixt** [google/gcm#126]
I'm providing the file name to play, but it doesn't appear to be working.

``` python
payload = {
    'to': device,
    'priority': 'normal' if data.get('background') else 'high',
    'notification': {
        'title': 'Roger',
        'body': data.get('text'),
        'badge': data.get('badge'),
        'sound': 'roger.mp3',
    },
    'data': data['custom'],
    'content_available': data.get('background', False),
}
```

**Comment by mohitsharma0690** [comment]
Right only default sound is supported for iOS and Android, https://developers.google.com/cloud-messaging/http-server-ref.

**Comment by blixt** [comment]
@mohitsharma0690 Is there any reason for this? Why can't the sound value be passed along to the APNs payload? This breaks our custom notification sound on iOS.

**Comment by ogeidix** [comment]
@blixt we are working on this. I will update this thread when we have news on the "sound" option.

**Comment by blixt** [comment]
@ogeidix I noticed you guys recently released a new version. Was the `sound` option added?

**Comment by ogeidix** [comment]
YES! You can find the details in the documentation (see "sound")
https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support

ps: this change is version independent for iOS, but it requires the app to be recompiled with google-play-services version 8.4 for Android.

**Comment by blixt** [comment]
Thank you!
