### ISSUE TITLE
IP range of GCM Server for firewall setting

### ISSUE THREAD

**Issue by VedantaBabaria** [google/gcm#134]
Hi Team,

We are facing some problem. 
As per company policy external ports and IPs are blocked by firewall which need to be white listed and hence our server is not able to connect to GCM Server. We need our Application Server-to-GCM Server Bi-Directional Connectivity.
So I want to know the IP ranges for GCM server?
I'm clear about ports:  5228, 5229, and 5230.

I have already read "https://developers.google.com/cloud-messaging/http". In this page, there is some guide how to set the firewall to use GCM push service as like below sentence.
"Note: If your organization has a firewall that restricts the traffic to or from the Internet, you need to configure it to allow connectivity with GCM in order for your GCM client apps to receive messages. The ports to open are: 5228, 5229, and 5230. GCM typically only uses 5228, but it sometimes uses 5229 and 5230. GCM doesn't provide specific IPs, so you should allow your firewall to accept outgoing connections to all IP addresses contained in the IP blocks listed in Google's ASN of 15169"

In the above sentence, they suggested " Google's ASN of 15169".
Is following link is list of IP Range which could work:-
http://bgp.he.net/AS15169#_prefixes
??

Awaiting for your earliest response.
Regards

**Comment by kroikie** [comment]
If you can allow connections by host name try:

port: 5228, host: mtalk.google.com
port: 443, host: android.googleapis.com

**Comment by vranacse** [comment]
hi @kroikie & @VedantaBabaria  did the solution worked . I am facing similar issue . Can you help?

**Comment by VedantaBabaria** [comment]
@vranacse : Hi! it is been a bit of a time since we encountered this issue. For our efforts at that time, it didn't worked for us as both our company's protocol for whitelisting ports and dependency of ports at GCM were high. So, we moved ahead with the workaround for the requirement.

And hey! why not try FCM instead, that won't be a problem?

**Comment by kroikie** [comment]
See the [docs](https://firebase.google.com/docs/cloud-messaging/concept-options#messaging_ports_and_your_firewall) for what ports and IPs need to be opened/whitelisted for FCM (and GCM):

> Ports to open for incoming messages:
>
> 5228
> 5229
> 5230
>
> IPs to allow outgoing connections:
> 
> All IP addresses contained in the IP blocks listed in [Google's ASN of 15169](https://ipinfo.io/AS15169).
