### ISSUE TITLE
GCM Android Client - Unable to get google-service.json configuration file

### ISSUE THREAD

**Issue by dbhasin86** [google/gcm#137]
When I click to get google-services.json configuration file, it just keeps loading and showing a progress bar in center. It doesn't open the page to input my app's package name and other details.

![image](https://cloud.githubusercontent.com/assets/320766/11696079/5f269ec6-9e67-11e5-9606-0249726f56ef.png)

**Comment by newacct** [comment]
I have the same problem. What was your conclusion?
