### ISSUE TITLE
Can not get a configuration file

### ISSUE THREAD

**Issue by tonn** [google/gcm#141]
After click blue-button in this page https://developers.google.com/cloud-messaging/android/client I get http://i.imgur.com/QDtP14w.png and error in browser console 

Load denied by X-Frame-Options: https://accounts.google.com/ServiceLogin?service=cloudconsole&osid=1&passive=true&authuser=0&continue=https://console.developers.google.com/mobilesdk/bootstrap/wizard/android?authuser%3D0%26hl%3Den%26cnturl%3Dhttps://developers.google.com/cloud-messaging/android/client%26cntlbl%3DContinue%2BAdding%2BGCM%2BSupport%26cntapi%3Dgcm&hl=en does not permit framing.

I tried it in firefox and chrome with the same result.

**Comment by tonn** [comment]
Error in chrome http://i.imgur.com/nxf1KT9.png

**Comment by dhristov** [comment]
Having the same issue. Firefox and Chrome on Ubuntu 12.04 LTS.

**Comment by tonn** [comment]
I didn't understend what was wrong, but I solved this problem by recreating project in google developer console.
