### ISSUE TITLE
gcm for chrome

### ISSUE THREAD

**Issue by VampireN** [google/gcm#145]
how to receive text messages push? I can not find where the data comes in chrome.I could not find the right information. help me please.

self.addEventListener('push', function(event) {
    console.log('Push message', event);
    var title = 'Новое сообщение';
    console.log('msg:',event.data);  // event.data undefined

**Comment by alastaircoote** [comment]
Unfortunately, it does not send to Chrome:

> A downside to the current implementation of the Push API in Chrome is that you can’t send any data with a push message. Nope, nothing. The reason for this is that in a future implementation, payload data will have to be encrypted on your server before it’s sent to a push messaging endpoint. This way the endpoint, whatever push provider it is, will not be able to easily view the content of the push message. This also protects against other vulnerabilities like poor validation of HTTPS certificates and man-in-the-middle attacks between your server and the push provider. However, this encryption isn’t supported yet, so in the meantime you’ll need to perform a fetch to get information needed to populate a notification.

(from https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web?hl=en)
