### ISSUE TITLE
Patch for /gcm-server/src/com/google/android/gcm/server/Sender.java

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#16]
```
fix the encoding issue.
```

Original issue reported on code.google.com by `changli....@gmail.com` on 5 Feb 2013 at 1:04

Attachments:
- [Sender.java.patch](https://storage.googleapis.com/google-code-attachments/gcm/issue-16/comment-0/Sender.java.patch)

**Comment by silvolu** [comment]
@kurthuwig would you mind to re-submit a Pull Request for this fix against this project?

**Comment by kurthuwig** [comment]
@silvolu I don't quite get it. Issue #17 has a better patch and has been closed. But I cannot see the fix of #17 in the master branch. IMHO the patch in #17 should be used and not the one in #16.

**Comment by silvolu** [comment]
@kurthuwig Sorry, most of this issues have been exported form the old google project, it's a bit hard to understand what went on and I completely missed your comment :)
Were you the author of the patch in issue #17?

**Comment by tjohns** [comment]
The patch in #17 was authored by mot...@naru.se. We could accept that patch, but it too would need to be submitted as a pull request by the original author.

(We can't accept patches without a CLA on file from the code's original author, and submitting a pull request is the easiest way to start that process. In this case, we do not have a pre-existing CLA on file from issue #17's author.)

**Comment by kurthuwig** [comment]
Here you go:

https://github.com/google/gcm/pull/100

**Comment by kurthuwig** [comment]
This issue can be closed as #17 is a duplicate and has been merged.
