### ISSUE TITLE
sender.send(...) returns very-very slow

### ISSUE THREAD

**Issue by csuccser** [google/gcm#161]
I'm experiencing a very strange issue with GCM backend API. 

This is my code: 

import com.google.android.gcm.server.Message;
import com.google.android.gcm.server.Result;
import com.google.android.gcm.server.Sender;

public Result sendMessageToGCM(PushUzenet pushUzenet, OauthTokens token) throws Exception {
        String apiKey = Utils.getResourceValue("GCMApiKey", "").trim();
        Message.Builder messageBuilder = new Message.Builder();
        switch (pushUzenet.getUzenetTipus()) {
            case KODSZO:
                messageBuilder.collapseKey("NetBank-kodszo");
                //1 óra
                messageBuilder.timeToLive(60 \* 60);
                break;
            case MEGEROSITO_JELSZO:
                //1 óra
                messageBuilder.timeToLive(60 \* 60);
                break;
            case SIKERES_BELEPES:
            case SIKERTELEN_BELEPES:
                //4 hét 
                messageBuilder.timeToLive(60 \* 60 \* 24 \* 7 \* 4);
                break;
            default:
                throw new Exception("Érvénytelen üzenet típus! -> " + pushUzenet.getUzenetTipus());
        }

```
    messageBuilder.addData(pushUzenet.getUzenetTipus().toString(), generateMessageWithAuthUUID(pushUzenet, token));
    Sender sender = new Sender(apiKey);
    return sender.send(messageBuilder.build(), token.getPushKliensId().trim(), 100);
}
```

When invoking "sender.send" method it does return after a long time. (15-30 minute or more)

What may cause this? I have no idea how to fix this issue. :( 

Have someone else experienced similar to this? 

Thanks a lot for helping!

**Comment by kroikie** [comment]
I'm not able to reproduce this, how often does this happen for you?

**Comment by csuccser** [comment]
Thanks for answering! It's a firewall issue and we don't find a correct solution to configure it. Our firewall cannot be configured by domain name, so we have to open the 443 port, but is not a good solution. What is the correct way to configure a firewall to be able to communicate with https://gcm-http.googleapis.com? We cannot find any IP range, or a list of IP addresses of this domain and it appears to be changing their IP address "randomly". If we open the entirely 443 port it works fine, but it is a security issue :(

**Comment by arnabc** [comment]
@csuccser The following info may help you (I picked it up from some of my old notes on GCM and Firewall issues)

> The Android device accesses the GCM servers on ports 5228-5230. If your organization has a firewall that restricts the traffic to or from the Internet, you'll need to configure it to allow connectivity with GCM. The ports to open are: 5228, 5229, and 5230. GCM typically only uses 5228, but it sometimes uses 5229 and 5230. GCM doesn't provide specific IPs. It changes IPs frequently. So you should allow your firewall to accept outgoing connections to all IP addresses contained in the IP blocks listed in Google's ASN of 15169 (https://www.dan.me.uk/bgplookup?asn=15169).

**Comment by kroikie** [comment]
Thanks @arnabc that's correct. You can find the note on firewalls [here](https://developers.google.com/cloud-messaging/http#message-with-payload--data-message)
