### ISSUE TITLE
how to send a notification with buttons

### ISSUE THREAD

**Issue by phate82** [google/gcm#164]
Hi all,
I developed two multi-platform (ionic) mobile apps (we can call them AppA and AppB) and a server with GCM functionality.
When the AppA user clicks a button to send a notification to a specific AppB user, AppA contacts the server, which gets the user's registration ID from the DB and sends the notification to the AppB user. Well, now I'd like that this status-bar notification had two buttons, so that the AppB user can properly respond to the server without opening the AppB. In other words, each of the two buttons should contact a specific REST API on the server. The notification should work on both Android and iOS devices.
Is it possible to build such a notification with the GCM server?
Thanks in advance.
Best regards.

**Comment by mohitsharma0690** [comment]
I think what you're looking for is the `click-action` key in GCM. Please read through the documentation here https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support
