### ISSUE TITLE
GCM for iOS generates empty Pods project

### ISSUE THREAD

**Issue by agentsim** [google/gcm#166]
Using a newly created, empty project with Xcode 7.2 on OS X El Capitan using CocoaPods 0.39.0, I'm trying to include GCM for iOS using the pod file below:

```
platform :ios, '8.0'

pod 'Google/CloudMessaging'
```

This results in no errors being thrown by cocoapods, and the xcworkspace is generated. The problem is, the Pods sub-project does not include any of the GCM targets or their dependencies. I've also tried specifying the target, as well as different versions of GCM, with the same result. As a sanity check, replacing `Google/CloudMessaging` by `FMDB` results in a properly configured project.

The following file [output.txt](https://github.com/google/gcm/files/114449/output.txt) is the output of `pod install --verbose`. It illustrates that despite finding all the dependencies, the "integrating target" message is only there for `Pods` and missing for all of the Google targets.

**Comment by agentsim** [comment]
Today's Xcode update (7.2.1) made no difference.

**Comment by mohitsharma0690** [comment]
I don't think this is an issue with Xcode. It's most likely the way our pod specs have been structured.

**Comment by mohitsharma0690** [comment]
This is not really a bug. Cocoapods generates a target for FMDB because FMDB needs to compile stuff (they pass in the custom sqlite stuff). GCM doesn't have this requirement since it's a static library so Cocoapod by itself wouldn't generate a target as you wouldn't need it.
