### ISSUE TITLE
Validating "Message" size

### ISSUE THREAD

**Issue by vishalkardode** [google/gcm#171]
After creating Message for GCM I want to validate the size is not exceeding the limit set by Google (4kb) . I can not see any implementation for validating size of message or updating any data key after message is created and validation fails.
Please suggest

**Comment by Ruud-cb** [comment]
I think you have to validate this yourself in whatever language you are writing. Just like if you are uploading an image to a website that has a limit of 1MB, you have to check yourself what size your image is and if it is to big you will get an error.

**Comment by mohitsharma0690** [comment]
@vishalkardode @Ruud-cb is right you should do the validation by yourself. The size validation happens internally within GCM and we do try to return a valid error if it's exceeded but it might happen that we fail silently.

Anyways what you want should be implemented by your app's side.
