### ISSUE TITLE
"Error=InvalidRegistration" when sending to topic on HTTP

### ISSUE THREAD

**Issue by dchdimitrov** [google/gcm#174]
According to the documentation I should be able to send to a specific topic when I change the
"to" to "/topics/myTopic". However every time I try to do this I get error "Error=InvalidRegistration".

When I change the "to" to a specific device token, the notifications work. When I try to send to a topic the error appears again.

I've also checked that there are devices registered for the topic.

**Comment by dchdimitrov** [comment]
Ok I found the problem. For some reason the "Contet-Type" of the request was changed by the 'request' npm module I was using.

**Comment by cblaze22** [comment]
What exactly does that mean because I am getting the same error?

**Comment by LuisCaceres123** [comment]
> What exactly does that mean because I am getting the same error?


In my case it was for not sending the data correctly in JSON format, in my case I did it like this:

let data = {
        "data":{
            "title": title
        },
        "to": '/ topics /' + topic
    }
$ .ajax ({
        type: 'POST',
        accepts: "application / json",
        headers: {
            'Authorization': 'key = YOUR-KEY',
            'Content-Type': "application / json"
        },
        url: 'https://fcm.googleapis.com/fcm/send',
        data: JSON.stringify (data),
        json: true,
        success: (data) => {
            console.log ("Sended");
        }
    });
