### ISSUE TITLE
GCM on iOS without using cocoapods

### ISSUE THREAD

**Issue by ymantijunk** [google/gcm#175]
Hi,

Is there any documented way to use GCM on iOS without using cocoapods? I personally prefer to take header/libraries and integrate myself than letting cocoapods messing up with my project (and it does).

Thanks

**Comment by nekrich** [comment]
Yep, and Carthage & Swift Package Manager support, please

**Comment by mohitsharma0690** [comment]
We will be looking into the Swift PM support but Carthage is not in our plans for now. 

The reason being GCM is pushed along with a suite of other Google libs which use one central system (cocoapods) to update stuff for now. We don't have any existing plans to add support for Carthage yet but that might change down the line.

**Comment by wuaschtikus** [comment]
Any way without Cocoapods would be highly appreciated!

**Comment by mohitsharma0690** [comment]
@wuaschtikus the only way I could think of right now is to grab the libs and public headers and link them together by yourself. That's what Cocoapods also does (amongst other things), but there shouldn't be anything preventing you from doing it by yourself.

**Comment by ymantijunk** [comment]
@mohitsharma0690 what a creative suggestion, how it never occurred to anyone..lol!! Sorry for being sarcastic but let's understand, Cocoapods is a dangerous concept, and I would say that it was short-sighted decision on Google's part to use it. No sensible developers would allow any third-party product to messup with project-settings and that's exactly what cocoapods does. XCode is pretty much straightforward in combining libraries and including in project and defining header paths and Cocoapad is seriously not needed for such  a trivial job. If you want to stay with Cocoapads, please do so but offer an alternatives, at least in terms of official documentation.

@wuaschtikus we did this and honestly the size increase is not worth the effort. Unlike Android where all necessary ingredients are already present in the platform, here quite a huge overhead needs to be compiled in order to support GCM. These extra overheads not worth the extra size especially when you want app to be small and quick to download even using slow cellular connection. Also note that GCM relies on APN internally and it's not a live connection like in Android because that's how Apple forces app to behave, this was quite a show-stopper for us to even consider adding GCM.

**Comment by mohitsharma0690** [comment]
@ymantijunk  :)

Anyways we are planning to have GCM be published as frameworks that can be integrated directly so that might help. Although there is no fixed timeline for this but hopefully we will be able to land them soon.

**Comment by wuaschtikus** [comment]
I highly appreciate this. Is this also true for other google services such as Google Analytics?

**Comment by mohitsharma0690** [comment]
Yes I believe so, it should be for all libs distributed as pods today.

**Comment by classified** [comment]
What about bitcode for ios?

**Comment by chriscoderdr** [comment]
Now it it's possible to use it without cocoapods https://firebase.google.com/docs/ios/setup#frameworks
Integrate without CocoaPods

If you don't want to use Cocoapods you can still take advantage of the Firebase SDKs by importing the frameworks directly.

Download the framework SDK zip (this is a ~100MB file and may take some time).
Unzip and see the README file for which Frameworks to include in to your project.
Add the ObjC linker flag in your Other Linker Settings in your target's build settings.

**Comment by mohitsharma0690** [comment]
Closing this since GCM (FCM) is now available via frameworks as mentioned above.

**Comment by akramShokri** [comment]
It is not the solution. I still need GCM framework for my work. I prefer not to use firebase as it itself also relies on GCM.

**Comment by chriscoderdr** [comment]
What do you mean? now GCM is FCM and it's part of firebase.

**Comment by wuaschtikus** [comment]
This is not an appropriate solution for automated builds - since I cannot use carthage (one of the most used dependency manager on ios) to integrate a download link.
