### ISSUE TITLE
iOS: No notifications after force quit, even with "priority": "high" param.

### ISSUE THREAD

**Issue by chlind** [google/gcm#183]
My ios App receive no notifications after force quit (i.e. by killing with the app switcher).
I did saw issue [#60](https://github.com/googlesamples/google-services/issues/60) and [#67](https://github.com/googlesamples/google-services/issues/67), so I add "priority" : "high" to my payload.
But still no notification received.

Here's my payload:
`{
  "notification": {
    "message" : "great match!"
  },
  "data": {
    "msg" : "great match!",
    "title" : "Portugal vs. Denmark"
  },
  "to" : "<MY-TOKEN>",
  "content_available" : true,
  "priority": "high"
}`

Here's the response:
`{
  "multicast_id": 6087504353579807411,
  "success": 1,
  "failure": 0,
  "canonical_ids": 0,
  "results": [
    {
      "message_id": "0:1460007343814475%c3a976d6c3a976d6"
    }
  ]
}`

I'm also saw [SO question](http://stackoverflow.com/questions/18856204/applicationdidreceiveremotenotificationfetchcompletionhandler-not-called) that says this might not be a bug on GCM side but rather because of iOS design.
But I'm not sure if it is the case.

So my question is: can iOS app receive GCM's notification after force quit?

**Comment by mohitsharma0690** [comment]
Yes that's an iOS feature. The `content_available` flag implies a sync notification which can be received by your app if it's either active or suspended (in the background). If the app was killed it won't be able to receive such notifications.

You can remove the `content_available` param and your app should receive a message even if it was killed (note you should still use the high priority flag).

**Comment by chlind** [comment]
If `application:didReceiveRemoteNotification:fetchCompletionHandler:` is not called if the app is killed, then how should I handle message in that case? More specifically, what method will be called in such situation?

Thanks for your response~
