### ISSUE TITLE
`content-available` is always true when `collapse_key` is set

### ISSUE THREAD

**Issue by vincentcr** [google/gcm#187]
When sending push notifications to iOS devices, it appears that `content-available` is always true  when `collapse_key` is set, whether we don't send the `content_available` field, or set it to false explicitly.

Example payload: 

```
{
 "registration_ids":["<snip>"],
 "notification":{"title":"a title","body":"some body","sound":"default"},
 "data": {
  "message":"a nessage"
 },
"content_available":false,
"time_to_live":900,
"collapse_key":"abcdef",
"priority":"normal"
}

```

**Comment by mohitsharma0690** [comment]
This seems like a bug. Will fix it in soon.

**Comment by mohitsharma0690** [comment]
This has been fixed. The fix should be live in a week or so. Please test again and let us know if you face any issues.

**Comment by vincentcr** [comment]
thanks 👍
