### ISSUE TITLE
Still having issues with GCM for iOS and Bitcode

### ISSUE THREAD

**Issue by atrepeklis** [google/gcm#189]
I have performed the pod update to GoogleCloudMessaging (1.2.0) but still getting the following issues when I have the Bitcode enabled. Is the issue back or am I missing something else?

`Pods/Google/Libraries/libGGLCloudMessaging.a(GGLContext+CloudMessaging.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by mohitsharma0690** [comment]
You should use GGLInstanceID v1.2.1

**Comment by atrepeklis** [comment]
I am using it already, any other idea?
From pod update:

`Using GGLInstanceID (1.2.1)`

**Comment by mohitsharma0690** [comment]
What version of Google pod are you trying with. Try the latest `2.0.4` one, that should have Bitcode. I just tested with the latest versions and it works fine for me.

**Comment by atrepeklis** [comment]
Indeed that fixed the issue my Google pod was stack at 1.0.7. I am wondering why the 'pod update' did not update the google main pod as well to the latest but anyhow. Thanks for the help!
