### ISSUE TITLE
possible IPv6 only issue when subscribing to topic

### ISSUE THREAD

**Issue by markusfassbender** [google/gcm#190]
Apple [announced](https://developer.apple.com/news/?id=08282015a) that every app has to support IPv6 only in June. So i've followed their [guide](https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16) to test IPv6 compatibility, see chapter "Test for IPv6 DNS64/NAT64 Compatibility Regularly".

When the device is connected to the IPv6 network my app receives a token, but does not subscribe to the topic afterwards. The logik is as follows:

```
    [[GCMService sharedInstance] connectWithHandler:^(NSError *error) {
        if(error == nil)
        {
            self.connected = YES;
            [self subscribeToTopic];
        }
        else
        {
            self.connected = NO;
            aslError(@"can not connect to GCM");
        }
    }];
```

When the device is connected to the usual WiFi-Network of my company the handler is called. When the device is connected to the IPv6 Network `connectWithHandler:` is called, but the handler itself will not be called. Can someone proof this behavior for his app? Are there any ideas why the handler is not called?

**Comment by mohitsharma0690** [comment]
Do you see any network errors in the system log? I don't think this is an IPv6 issue (haven't really tested it though.

**Comment by markusfassbender** [comment]
thanks for your comment. there are no network specific logs...
