### ISSUE TITLE
App Documents directory used for cache files

### ISSUE THREAD

**Issue by vladogrigorov** [google/gcm#192]
I download these GCM pods:

```
Using GGLInstanceID (1.2.1)
Using Google (2.0.4)
Using GoogleCloudMessaging (1.2.0)
Using GoogleIPhoneUtilities (1.2.0)
Using GoogleInterchangeUtilities (1.2.0)
Using GoogleNetworkingUtilities (1.2.0)
Using GoogleSymbolUtilities (1.1.0)
Using GoogleUtilities (1.3.0)

```

Then I copy library and header files to my project, which does not use CocoaPods. GCM works fine, however it always creates these files in the Documents directory:
- com.google.iid-keypair.plist
- com.google.iid-tokens.plist
- g-checkin.plist
- rmq2.sqlite

I see the issue #120 is closed, but I can't find GCM version where this has been fixed.

**Comment by vladogrigorov** [comment]
This issue is easily reproduced by running the latest version of the sample project. Follow the steps as described at [https://developers.google.com/cloud-messaging/ios/start](https://developers.google.com/cloud-messaging/ios/start):
1. Enter "pod try Google" in Terminal, select GcmExample.xcodeproj.
2. Generate GoogleService-Info.plist and add that configuration file to the project. 
3. Additionally, open sample application's info.plist file and add the key UIFileSharingEnabled with value YES. 

When running the sample on a device, the four files are created in Documents directory.

Apps that write cache files to Documents directory may be rejected by Apple's App Store. Please advise how to solve this issue.

**Comment by mohitsharma0690** [comment]
Yeah this is a known issue, we will move them away from Documents in the next update. 

P.S: This wasn't fixed in GCM either, will do it for real this time :)

**Comment by ayuzhin** [comment]
When the next update?

**Comment by mohitsharma0690** [comment]
Sadly we missed the current deadline for this but it would surely be there in the next update which might take a couple of weeks I believe.

**Comment by LieutenantKernel** [comment]
I also am having trouble with this. I need to deploy my application soon but I don't want my users interacting with these files in the documents directory. I don't want to have to use another service for this.

**Comment by mohitsharma0690** [comment]
This has been fixed in the latest release, please checkout the latest release and let us know if you've any issues.

**Comment by mikemonteith** [comment]
When will this be released to CocoaPods? https://cocoapods.org/pods/GoogleCloudMessaging

**Comment by mkll** [comment]
The latest available version of GCM for iOS (obtained via CocoaPods) still creates at least `rmq2.sqlite` in the Documents directory. This is just ridiculous. Obscenely ridiculous.

**Comment by mikemonteith** [comment]
@mkll It doesn't look like this update has been released to CocoaPods yet ("Last release Feb 2016").

@mohitsharma0690 Any idea when it will be released?

**Comment by jielu** [comment]
We have updated FirebaseMessaging pod since v1.1.1 and FirebaseInstanceID pod since v1.0.8 to remove all the files form Documents directory. Unfortunately we don't have an ETA to fix this issue for GoogleCloudMessaging library. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

p.s. fyi. unfortunately this is not the best place to receive support for this type of issues now.
Please choose one of the available channels from https://firebase.google.com/support/
