### ISSUE TITLE
GCM not send notification when app is closed 

### ISSUE THREAD

**Issue by ajaysaini95700** [google/gcm#198]
i am not getting push notification when app is closed why?

**Comment by kroikie** [comment]
Could you please show the request that you are using to send the notification? Also what are you using to receive the notification?

**Comment by CongBaDo** [comment]
@ajaysaini95700  you mean the app is still receive notification if the app is in foreground and background?

**Comment by ajaysaini95700** [comment]
Some times When app is in foreground or background or closed . Then
notification does not come . It comes after 15- 20 minutes. How remove
notification delay time

**Comment by CongBaDo** [comment]
@ajaysaini95700 What do you mean "closed", clear the app in recent app or press back button

**Comment by ajaysaini95700** [comment]
Closed means
Remove app from background

**Comment by Atrix1987** [comment]
@ajaysaini95700 pls provide some details. FCM library version ? Client-side code ?  Where are you sending it from ? if on your own then what are the parameters you are sending it with ?

**Comment by ogeidix** [comment]
Hi @ajaysaini95700,
unfortunately this is not the best place to receive support for this type of issues.
Please choose one of the available channels from https://firebase.google.com/support/
