### ISSUE TITLE
GCM for both Android and iOS app identifiers

### ISSUE THREAD

**Issue by jondot** [google/gcm#199]
Hi,
Must both iOS and Android app identifiers be the same in order to view both iOS and Android diagnostics data in Play Developer console?

Sender is the same for both cases

**Comment by kroikie** [comment]
Sorry but the diagnostics in the Play Developer console are [only for published Play Store apps](https://support.google.com/googleplay/android-developer/answer/2663268).

**Comment by jondot** [comment]
Sorry, assuming both apps are already published. Any idea regarding app ids?

**Comment by kroikie** [comment]
If your Android app is published on the Google Play Store then you can get diagnostics via the Play Developer console otherwise you cannot. App ids are not relevant in this case.

**Comment by jondot** [comment]
@kroikie sorry to stretch this thread, but if what you're saying is that GCM diagnostics is available for published Play apps which is to say Android apps (or, at least, NOT iOS apps), then it stands in conflict with everything that I'm reading, such as [here](https://developers.google.com/cloud-messaging/diagnostics) which is stating that it is available for iOS apps, [on this tweet](https://twitter.com/googledevs/status/609119907423395841) which is saying "diagnostics and topic messaging is coming for iOS", and [for the "Sent to APNS" data](https://support.google.com/googleplay/android-developer/answer/2663268?hl=en) section, stating that there is diagnostics data for APNS.

**Comment by mohitsharma0690** [comment]
@kroikie @jondot AFAIR the diagnostic data is available for both iOS & Android. The amount of stuff on iOS might be a bit limited though. I'm not fully sure how to get that data though or if it requires the same app ids or not.

**Comment by jondot** [comment]
@mohitsharma0690 it looks like everything Google have put out, in form of API and docs indicate that there _is_ diagnostics for iOS like you're saying (clearly there are fields like "Sent to APNS status" in the docs), however I'm not sure how to proceed here.
Any information or contacts you could give me so that I can continue to investigate?
