### ISSUE TITLE
maven artifact in light of FCM migration

### ISSUE THREAD

**Issue by ghost** [google/gcm#200]
Is the maven artifact com.google.gcm:gcm-server intended to work with fcm?
Will it continue being hosted as gcm, or will there be a name migration?

**Comment by kroikie** [comment]
GCM will continue to work as usual, you may choose to update the endpoints but this is not necessary at this time since both the fcm and gcm endpoints will provide the same services.

**Comment by stevenzeck** [comment]
@kroikie sorry to resurrect an old issue. The only Maven version is 1.0.0 which doesn't have the updates that point to the FCM endpoint. Do we have to build from source to do this? Or is there a FCM SDK alternative to this?

**Comment by kroikie** [comment]
Use the Firebase Asmin SDK instead. https://firebase.google.com/docs/admin/setup

**Comment by stevenzeck** [comment]
Is there a migration guide?

**Comment by kroikie** [comment]
There is no migration guide for this, however the usage is very similar.
