### ISSUE TITLE
Gcm Sender Id (Project Number)

### ISSUE THREAD

**Issue by sandipborad** [google/gcm#203]
Hey ,
In our project  as so long time ago few developer create project for Gcm and generate server key & i ma a team leader of my company and  in my company previous developer was resign before i am joining so i am trouble at this time that can you give me that person email id only so i can catch up that in which account that project is created 
My project Number is  :  886912565648

**Comment by kroikie** [comment]
Sorry you find yourself in that position:
I'd start with Google Cloud Platform support https://cloud.google.com/support/
