### ISSUE TITLE
iOS GCM multiple app. One app overrides another app's token.

### ISSUE THREAD

**Issue by RuslanKham322** [google/gcm#208]
I have two apps. But i use one server token (sender id). Where is issue, if both app is installed on one device.
After launching first app, i receive Token1. After launching second app, i receive Token2. If now launch first app, it will have Token2! I.e. second app overrides first app's token. But this Token2 work only for second app. Token1 will still work for first app, but it is returning Token2.
Is it bug, or i must use different sender ids for different apps?

**Comment by mohitsharma0690** [comment]
This is very strange. So you seem to be getting token2 from app1 after you've installed app2. 

Are you using the same credentials (senderID) for both apps? Also the tokens are cached on the client so it seems very strange that somehow app2 is overriding app1's token. 

Also can you contact Firebase Support and provide more info i.e. the tokens for your two apps, senderID etc.. Please let the support people know that they should contact me (Mohit) with the bug.

**Comment by RuslanKham322** [comment]
Thanks, i'll contact with the support!

**Comment by RuslanKham322** [comment]
@mohitsharma0690  Support didn't answer me. Maybe, i wrote issue in wrong place.
Anyway, i located problem. My apps are using keychain sharing to share some data. If i turn off it, all become good. Seems like GCM saving its tokens to keychain.
If you have contact with support, say them about this.

**Comment by mohitsharma0690** [comment]
Hmm yeah GCM uses keychain to store the sensitive stuff. I guess this would be an issue with sharing enabled.

**Comment by RuslanKham322** [comment]
It's a bug and i must wait the fix? Or it's a feature and i can't use keychain sharing with GCM?
