### ISSUE TITLE
GCM Old version duplicate registration issues

### ISSUE THREAD

**Issue by leeminsuek** [google/gcm#210]
"gcm.jar" used to set up the project 
### I used to get a token

   **public static String getPushToken(Activity ac) {
        // regist push token
        GCMRegistrar.checkDevice(ac);
        GCMRegistrar.checkManifest(ac);
        String regId = GCMRegistrar.getRegistrationId(ac);
        if (regId.equals("")) {
            Log.v(TAG, "GCM registe request");
            GCMRegistrar.register(ac, apikey);
            regId = GCMRegistrar.getRegistrationId(ac);
            Log.v(TAG, "registe done" + regId);
        } else {
            regId = GCMRegistrar.getRegistrationId(ac);
            Log.v(TAG, "Already registered " + regId);
        }
        return regId;
    }**

but..the prefix caught a token.

ex)  |ID|1|:fS9LbiGWV6I:token value - ~

Was the code was well used , it became more than any moment. Ask for help

**Comment by kroikie** [comment]
gcm.jar is no longer supported please consider using the now recommended Firebase Cloud Messaging.
