### ISSUE TITLE
FCM : Message replacing when both user sent message at a time

### ISSUE THREAD

**Issue by VamsiYQ** [google/gcm#224]
I have implemented One to One chat in android using FCM, When both users sending message in same time the message is replacing like 

Example : Time of Input User 1 @9:00 AM  User2 @9:02 AM  
User 1(Hi)        -->        User 2 (Hello)         ----->       User 1(Hello)      < ---->           User2 (Hi) 

If both the users sends message  with 3 seconds message is replacing like above.

Can any one give solution , Thanks in advance.

**Comment by ogeidix** [comment]
Hi @VamsiYQ ,
unfortunately this is not the best place to receive support for this type of issues.
Please choose one of the available channels from https://firebase.google.com/support/
