### ISSUE TITLE
Please deploy artifacts to Maven Central Repository

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#23]
```
Since gcm-server should be broadly available from server-side projects of 
Android apps, please deploy the artifacts to public Maven Repository such like 
Sonatype OSS Maven Repository. There is someone who is providing unofficial 
repository (https://github.com/slorber/gcm-server-repository) , but I think 
this should be done officially.

I created `mavenize` branch to build and deploy gcm-server with using Maven. 
And also, I set up Maven Ant Tasks in build.xml to enable deployment via Ant.

https://code.google.com/r/yamashita-gcm/source/browse/?name=mavenize

The following is the summary of changes:

1. Add pom.xml to build and deploy with using Maven
2. Setup Maven Ant Tasks to deploy with using Ant
3. Assign unique development version name in Maven style (1.0.3-SNAPSHOT)
4. Change project structure to Maven style

```

Original issue reported on code.google.com by `yamash...@geishatokyo.com` on 8 May 2013 at 1:47

**Comment by onsails** [comment]
+1

**Comment by xuwei-k** [comment]
+1

**Comment by bogdanzurac** [comment]
Finally found a thread about releasing a maven version of gcm-server. I'm currently using this artifact http://search.maven.org/#artifactdetails%7Ccom.ganyo%7Cgcm-server%7C1.0.2%7Cjar
It would be more than awesome if this would be released. I'm actually quite intrigued as to why it hasn't been an official Maven release of this library at all. I know you can just call the API yourself or use the jar file, but come on... this is Maven we're talking about. Nothing beats that simplicity.

**Comment by sv3k** [comment]
+1
Strange that is has not been done yet.

**Comment by benblack86** [comment]
+1

**Comment by nsauro** [comment]
+1

**Comment by reeve** [comment]
+1

**Comment by yellowbunchu** [comment]
+1

**Comment by Syntxx** [comment]
+1

**Comment by silvolu** [comment]
It took some time, but we're working on it. Thanks for the patience :)

**Comment by HNygard** [comment]
+1

**Comment by Polve** [comment]
+1

**Comment by gresrun** [comment]
:+1:

**Comment by maksimu** [comment]
+1. Any ETA on when it will be available on Maven?

**Comment by maksimu** [comment]
Just added Maven to my fork of this library: https://github.com/maksimu/gcm

Feel free to check it out.

To add manually Maven dependency to your project you can do the following steps:
1. Build .jar file: `mvn clean bulild`
2. Execute in the root directory of the project: `mvn deploy:deploy-file -Durl=file:///[FOLDER WITH YOUR OTHER MANVEN PROJECT]/repo -Dfile=target/rest-client-1.0-SNAPSHOT.jar -DgroupId=com.google.gcm -DartifactId=rest-client -Dpackaging=jar -Dversion=1.0-SNAPSHOT`
3. Then in your existing maven project' pom.xml file add the following:

```
    <dependencies> 
      <!-- Other dependencies -->

      <dependency>
            <groupId>com.google.gcm</groupId>
            <artifactId>rest-client</artifactId>
            <version>1.0-SNAPSHOT</version>
     </dependency>
   </dependencies>


     <repositories>
      <!-- Other Repositories -->
        <repository>
            <id>project.local</id>
            <name>project</name>
            <url>file:${project.basedir}/repo</url>
        </repository>
    </repositories>
```

**Comment by jlbelmonte** [comment]
:+1:

**Comment by michaelarusso** [comment]
We've just forked this and packaged it for maven, releasing it to maven central:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.apigee.gcm%22
https://github.com/apigee/gcm
1.0.0 points to the current of master branch.

We kept the existing file structure the same and just added a pom.xml: `client-libraries/java/rest-client/pom.xml`.  We kept it this way so we can easily incorporate changes from this source repo until it's published by Google into maven central officially.

**Comment by ayjindal** [comment]
Is it going to be available officially anytime soon?

**Comment by kroikie** [comment]
Hi @ayjindal I'm actively working on officially getting this out. It should be out very soon.

**Comment by jewest27** [comment]
@ayjindal in the meantime you could use the one with the io.apigee.gcm package on maven central if you needed it...

```
<dependency>
    <groupId>io.apigee.gcm</groupId>
    <artifactId>gcm-server</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Comment by ayjindal** [comment]
@jwest-apigee Thanks! I'll surely give it a shot to get started.
@kroikie Looking forward to its coming. Thanks.

**Comment by avboy72** [comment]
Is this an official google project?  If so, why is it not published in Maven?

**Comment by kroikie** [comment]
The library is available now:

Group: com.google.gcm
Artifact: gcm-server
Version: 1.0.0

**Comment by Polve** [comment]
Shouldn't the last version be 1.0.3 or 1.0.2?

**Comment by RishabhJain1603** [comment]
Hi All,
I am beginner to maven and finding it difficult to migrate my project from gradle to Maven.
For Push notification code, that I have using from below link in gradle environment is working fine:
$ git clone https://github.com/googlesamples/google-services.git

But when i am trying to use it in my Maven and adding  the following dependency to my pom.xml file:
<dependency>
            <groupId>com.google.gcm</groupId>
            <artifactId>gcm-server</artifactId>
            <version>1.0.0</version>
        </dependency>

And when I am trying to define receiver in my manifest file, I am getting the error.Not able to import any of the Cloud Messaging API in my code.
<receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="gcm.play.android.samples.com.gcmquickstart" />
            </intent-filter>
        </receiver>

Please help me to resolve the error.
Thanks for the help.

I am using the sample given at below link:

Able to run in gradle environment successfully but now due to some client requirement I need to migrate my project to Maven.

**Comment by kroikie** [comment]
@avboy72 It is available via maven now. Sorry for the delay.
@Alessandro We could have gone with 1.0.3 but decided to go with v1.0.0
since this is the first release to maven.
@RishabhJain1603 not sure where the issue related to the client library,
create a new issue if you believe it is so. If it is a maven issue then a
question on SO may be better place.

**Comment by Polve** [comment]
@kroikie I see, but that's quite strange: who is gonna use an old release just to use the google artifact?
Please release at least 1.0.2 :-)

**Comment by pushbit** [comment]
@Polve, if I understand the situation correctly, the version number has simply been "renamed" to 1.0.0 and is based on the latest code as of 2016-01-16.  We needn't worry that an ancient version of the library was dug up and released to Maven Central.

**Comment by Polve** [comment]
@pushbit Thanks for the info, let's hope it's how you say.
Anyway I find this very strange and confusing: what was the problem in calling the release 1.0.4 instead?

**Comment by silvolu** [comment]
The version numbers above 1.0.0 come from when the project was on google code and binaries were distributed as downloads in a dist folder inside the project.
Given that we've moved to maven and it's the first package that we published to maven, and that the old packages are basically not available anymore, it seemed a cleaner solution to restart versioning from 1.0.0.

**Comment by RishabhJain1603** [comment]
Using the above Dependency in my pom.xml file, I am not able to import  any of Google Cloud Messaging API. It is giving error while writing below lines:
``GoogleApiAvailability apiAvailability = GoogleApiAvailability.getInstance();

I am not able to import any of the Google Cloud Messaging API's in my code.
Thanks for the help.

**Comment by renekabagamba** [comment]
Thanks @silvolu and @kroikie. Any chances now that gcm was replaced by fcm that we will have the same availed on maven central also.
