### ISSUE TITLE
Push notification sent to different notification EndPoint

### ISSUE THREAD

**Issue by manishkapoor108** [google/gcm#230]
Hi,

It has been observed that server is sending Push notification to one notification endpoint( registered through GCM) but it is getting delivered to some other notification endpoint (registered through FCM).
This is leading to delivery of Push Notifications to the users who are not intended to receive that.
The problem has been observed with notification endpoint : _APA91bGQdgZ_hp2VR4tL-fN7r04hCZTh6EHAEKrkhQ6DSuV1CGPSPgTSbayEUZFa3Ochvyjdjfc30HI2gylDbsSAL_ETJSBE1XVN6w8bE2-qrNQQpoSE8h0TuMyEOEjGTJ0RFeU7wbVm_

Please help

**Comment by ogeidix** [comment]
Please report issues like this to Firebase Support:
https://firebase.google.com/support/contact/bugs-features/

Thanks.
