### ISSUE TITLE
Is this lib still maintained?

### ISSUE THREAD

**Issue by odaynasser** [google/gcm#238]
I intend to use this library for my project, is it still being maintained?

**Comment by ogeidix** [comment]
Hi @odaynasse,
this library is community mantained.
A more maintained library is included in the Firebase Admin SDK, but currently is Node.js only.
https://firebase.google.com/docs/cloud-messaging/admin/
https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging
