### ISSUE TITLE
Issue Regarding Notification Display.

### ISSUE THREAD

**Issue by amitthorat** [google/gcm#252]
Hi,

I have implemented GCM push notification for my android application. It's working properly except two devices i.e. OnePlus 3T and Oppo A37F.

For OnePlus 3T, device is not registering to GCM and for Oppo, device is registered successfully but not getting notification in notification drawer.

**Comment by ogeidix** [comment]
Hi @amitthorat,
this could be a problem with those specific devices.
Please report it to the manufacturer of the devices to make them aware that their customization to stock android are preventing push notifications from working.
