### ISSUE TITLE
gcm 1.0.3 release

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#33]
```
There are quite a few fixed issues already available and I was wondering when 
you are planning to release the new 1.0.3 version?
```

Original issue reported on code.google.com by `alex.obj...@gmail.com` on 29 Jul 2013 at 12:45

**Comment by esigma5** [comment]
Hi there. It's been five months. Any plan to release a new version?

**Comment by dominikkontner** [comment]
Hi,

Maybe you want to try my new gcm rest client. https://github.com/dominikkontner/GCM

**Comment by silvolu** [comment]
I guess you're talking about http://mvnrepository.com/artifact/com.ganyo/gcm-server/1.0.2? IF so, we don't maintain that repo. @kroikie is working on updating the library and publish to an official Google repo. Stay tuned, and thanks for the patience.

**Comment by esigma5** [comment]
I am talking about the oficial gcm-server library (which I think this repo represents). Didn't know about that one, but if google will use it as the next release, it's nice to know that a least something will get released. Let us know!

**Comment by silvolu** [comment]
@esigma5 oh ok, lot of people are asking about releasing on Maven, and my mind went straight there :)

**Comment by kroikie** [comment]
There is a release process in place now so updates to this library can be made available more quickly.
