### ISSUE TITLE
Format of request to `/gcm/v1/device/register/`

### ISSUE THREAD

**Issue by iqbalhusen** [google/gcm#55]
Could anyone please reply a `curl` `POST` request to register a device? And how the `name` field in `Device` model is generated?

**Comment by alibitek** [comment]
@iqbalhusen You can't register devices on the server. The Google Cloud Services does it on your behalf **on the client**, if you tell it to. You get back a registration token that you send to your server, and from your server you tell GCM to send a message to the device using that token and an API key that authenticates your server. As per https://developers.google.com/cloud-messaging/http

**Comment by silvolu** [comment]
This doesn't look like a GCM endpoint, not sure what the problem is here.
