### ISSUE TITLE
Does the legacy client work on AOSP?

### ISSUE THREAD

**Issue by h-2** [google/gcm#56]
Is it possible to use the legacy client to receive push notifications on plain AOSP devices, i.e. without Play services or other proprietary components?

If not, is there another way to do it receive push notifications without relying on proprietary software? Thanks!

**Comment by silvolu** [comment]
No, Google Cloud Messaging doesn't work on devices without Google APIs.

**Comment by eladnava** [comment]
An alternative option is Pushy (https://pushy.me/), a highly-reliable push gateway for Android apps that works independently from GCM, using its own background MQTT connection.

Full disclosure: I founded Pushy.
