### ISSUE TITLE
Create new demo without using deprecated libraries

### ISSUE THREAD

**Issue by akousmata** [google/gcm#57]
This is an awesome new demo which explains 99% of my questions about how GCM works and how to implement it.  However, the demo itself uses deprecated libraries such as the Message.Builder which is part of the old GCM helper library.  So my questions are answered, but you are using things in your demo which Google has basically taken away from all the other developers.  

This demo is far less helpful when you use these libraries as when I try to use some of the testing to emulate a server in my own application, I have to dig around on the internet to find copies of a library Google doesn't want me to have anymore and then either copy the code into classes I create or reference a library and deal with all the "obsolete" warnings.

**Comment by vladimirionescu** [comment]
Hi Nathan,

Thank you for the feedback! I am glad you find this sample app useful.
The code for the Message class is not coming from a deprecated library, you can find it here: https://github.com/google/gcm/blob/master/gcm-demo-app/src/main/java/com/google/android/gcm/demo/logic/Message.java
This class used to be part of a demo for a server communicating with GCM, and that demo is indeed deprecated. We may release a demo doing just server-side communication in the future, but there is currently no timeline for that.

Best regards,
Vlad

**Comment by akousmata** [comment]
Ahh, ok, thanks.  I guess I made some false assumptions.
