### ISSUE TITLE
Did anyone get the PeriodicTask running?

### ISSUE THREAD

**Issue by learnNcode** [google/gcm#58]
Tried testing the GcmNetworkManager, OneOffTask and PeriodicTask. OneOffTask did well...but unable to get PeriodicTask running. Did anyone encounter this issue? Nothing just happens unable to debug too.

**Comment by vladimirionescu** [comment]
Hi,

For periodic tasks, the period needs to be greater than 30 seconds, otherwise they will not be scheduled to protect against abuse.

Best regards,
Vlad
