### ISSUE TITLE
 Make GCMRegistrar.checkManifest() aware of Jelly Bean changes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#6]
```
If an app is targeted to Jelly Bean:

- The broadcast receiver does not need the category
- The C2D_MESSAGE is not required

GCMRegistrar.checkManifest() should take the version in account and disable 
these 2 checks when running on target 16.
```

Original issue reported on code.google.com by `felip...@google.com` on 7 Aug 2012 at 7:08

**Comment by silvolu** [comment]
Please migrate to the new Google Play Services [InstanceID API](https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID).
