### ISSUE TITLE
Listening to gcm on chrome not working anymore!

### ISSUE THREAD

**Issue by mohammedpascal** [google/gcm#65]
Hi, 
I noticed that registering for gcm on chrome doesn't work anymore!
chrome.gcm.onMessage.addListener(messageReceived);

Even the chrome sample gcm-notifications doesn't work

https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/gcm-notifications

**Comment by Bupyc** [comment]
Confirm. Google kill push notification in chrome :(

**Comment by ogeidix** [comment]
Hi all,

Thanks for your bug reports.
We indeed had an issue on GCM that started few days ago and affected a small percentage of users, mainly on Chrome.
As of today the issue should be completely fixed.

If you still have problems with this, please update this bug on chromium bugtracker: https://code.google.com/p/chromium/issues/detail?id=503186
