### ISSUE TITLE
GCM for iOS can't make configuration file with Bundle ID containing a number as first character

### ISSUE THREAD

**Issue by msun** [google/gcm#66]
I am trying to set up Google Cloud Messaging for iOS, and want to make a configuration file.

Go to https://developers.google.com/cloud-messaging/ios/start?ver=objc scroll down a bit, and press the blue "Get a Configuration File" button.

I want to use an iOS Bundle ID that has a number as the first character, for example "com.3foo.bar", but it will not allow it. A few days ago this was allowed, and I was able to create a configuration file, but for some reason it doesn't work anymore. Note that such a Bundle ID is permitted in Xcode and for use in Apple Developer program.

**Comment by tjohns** [comment]
Thanks for the report.

I've passed this issue on to the team who maintains that code, and it is being tracked internally as b/22173232.

**Comment by ghost** [comment]
@tjohns : could you please reply to https://github.com/google/gcm/issues/64 ?

**Comment by msun** [comment]
It seems this has been fixed.
