### ISSUE TITLE
GCM Network Manager has no way to send parameters

### ISSUE THREAD

**Issue by NitroG42** [google/gcm#67]
There is a big flaw with the new GCM Network Manager, when we create a task : 

``` java
OneoffTask myTask = new OneoffTask.Builder()
                          .setService(MyGcmTaskService.class)
                          .setExecutionWindow(
                              5 * DateUtil.MINUTE_IN_SECONDS, 15 * DateUtil.MINUTE_IN_SECONDS)
                          .setTag("test-upload")
                          .build();
     GcmNetworkManager.get(this).schedule(myTask);
     ...

     // Implement service logic to be notified when the task elapses:
     MyUploadService extends GcmTaskService {
         @Override
         public int onRunTask(TaskParams params) {
             // Do some upload work.
             return GcmNetworkManager.RESULT_SUCCESS;
         }
     }
```

TaskParams has only one member, a String ! (limited to 100 characters btw).
How are we supposed to start a network task without giving any arguments ? 
It really needs a Bundle to be effective.
Except for this issue, this service looks very useful for in-app networking tasks.

**Comment by alibitek** [comment]
@NitroG42 No. You have misinterpreted what the TaskParams class is for. (the name might be the culprit)

The tag value inside the TaskParams represents an **identifier** for the task that is currently running, which you specify using the [setTag](https://goo.gl/qnFB4u) method when you create a Task through one of the [Task.Builder](https://developers.google.com/android/reference/com/google/android/gms/gcm/Task.Builder) subclasses:
- [OneoffTask.Builder](https://developers.google.com/android/reference/com/google/android/gms/gcm/OneoffTask.Builder)
- [PeriodicTask.Builder](https://developers.google.com/android/reference/com/google/android/gms/gcm/PeriodicTask.Builder) 

This tag will be returned at execution time to the onRunTask method through the getTag() method of the TaskParams object. This is useful in the case when you have multiple tasks and you will be called back by the scheduler on the same GcmTaskService object.

Also as the [GcmTaskService](https://developers.google.com/android/reference/com/google/android/gms/gcm/GcmTaskService) class docs says: `Bear in mind that your service may receive multiple calls from the scheduler at once (specifically if you've made multiple schedule requests that overlap). If this is the case, your implementation of onRunTask(com.google.android.gms.gcm.TaskParams) must be thread-safe.`

So, inside the onRunTask you provide the logic for your task execution **and** you have to keep track of the state that you need for that particular task to do what you want.

See the [TaskSchedulerService](https://github.com/google/gcm/blob/master/samples/android/gcm-demo/src/main/java/com/google/android/gcm/demo/service/TaskSchedulerService.java) in the provided gcm example where you have a collection of tasks, and you store [TaskTracker](https://github.com/google/gcm/blob/master/samples/android/gcm-demo/src/main/java/com/google/android/gcm/demo/model/TaskTracker.java) objects (the state/logic for a task) in a SimpleArrayMap at the tag's key inside the [TasksCollection](https://github.com/google/gcm/blob/master/samples/android/gcm-demo/src/main/java/com/google/android/gcm/demo/model/TaskCollection.java) class.
https://github.com/google/gcm/search?utf8=%E2%9C%93&q=TaskSchedulerService

**Comment by NitroG42** [comment]
I understood the purpose of the tag, and how the Tasks mecanism works, but I thought it could be improved if the dev had not to handle all the task management behind.
Basically, on a gcm push reception, the app start a new task with some params, onRunTask is called, we do the work here, and send back the result.
A bit like how handleMessage of a Handler works.

Anyway, I'm using your exemple for now, I just hope it will be more simple to implement in the future.
Thank you for your answer !

**Comment by 43matthew** [comment]
NitroG42 you are right that this would make the task easier to use.
In fact, we are working on this for a future release of Play Services.

**Comment by vRallev** [comment]
I think this ticket can be closed. Starting with version 7.8.0 you can pass extras.

**Comment by mjwilliams43** [comment]
Indeed, we added this feature based on feedback from tickets like this and internal requests. Thanks for the feedback, and if you have any other requests please pass them along.

**Comment by wdayanand** [comment]
You can use JobScheduler and use setExtras() method
http://developer.android.com/reference/android/app/job/JobScheduler.html
