### ISSUE TITLE
GCM-Server 3.0 Library

### ISSUE THREAD

**Issue by ZakTaccardi** [google/gcm#68]
Where is the java library that supports GCM 3.0 server side?

I have an app engine server, and I need some java code to implement GCM 3.0 to send downstream messages.

The current release of gcm-server (1.0.2) does not have support for GCM 3.0. What is going on?

**Comment by tjohns** [comment]
The REST client for GCMv1 is here:
https://github.com/google/gcm/tree/master/client-libraries/java/rest-client

We're working on a client library that uses CCS/XMPP, which will allow us to support all of the GCMv3 features. In the meantime, instructions on interfacing with the CCS server directly are here: https://developers.google.com/cloud-messaging/ccs
