### ISSUE TITLE
Please ensure KVM is properly installed and usable.

### ISSUE THREAD

**Issue by ghost** [google/gcm#69]
I am really struggling to fixed this issue from last few weeks. Could anyone please guide me?
I am using latest ubuntu machine.

`/home/Sdk/tools/emulator -avd Nexus_5_API_22_x86 -netspeed full -netdelay none
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM is not installed on this machine (/dev/kvm is missing).`

**Comment by tjohns** [comment]
This is not a GCM issue, and therefore this is the wrong place to report this. (The android-discuss mailing list would be more appropriate.)

That said, I recommend reading the advice in this AskUbuntu StackExchange thread on enabling KVM support: http://askubuntu.com/questions/552064/how-can-kvm-be-located-by-android-studio-on-ubuntu-14-04-lts

There's also an article on the Ubuntu wiki that goes over this in greater detail: https://help.ubuntu.com/community/KVM/Installation

In particular, run the installation steps listed there, make sure you have "VT" support enabled in your BIOS (folks often forget this step), and run the kvm_ok command to verify that you've done all of the above properly.
