### ISSUE TITLE
GCM Topic Messaging not working on some versions of Play Services

### ISSUE THREAD

**Issue by RockoDev** [google/gcm#74]
I've been implemented the new version of GCM with topic messaging, but some devices doesn't receive notifications via topics.

Here some tests I've made with devices running different versions of Google Play Services:

Success:
Google Play Services v7.6.03 (XXXXXX-438) with Android M - Nexus 5
Google Play Services v7.5.74 (XXXXXX-438) with Android 5.1 Lollipop - Nexus 5
Google Play Services v7.5.74 (XXXXXX-438) with Android 5.0.2 Lollipop - OnePlus One

Failed:
Google Play Services v7.5.74 (XXXXXX-440) with Android 5.0.2 Lollipop - Galaxy S6 Edge
Google Play Services v7.5.74 (XXXXXX-440) with Android 5.0.2 Lollipop - Galaxy S6 Edge (another one)
Google Play Services v7.5.74 (XXXXXX-436) with Android 5.0.2 Lollipop - Moto G 2nd gen.
Google Play Services v7.5.74 (XXXXXX-436) with Android 4.4.4 Kitkat - Moto X 1st gen.
Google Play Services v7.5.74 (XXXXXX-436) with Android 4.4.4 Kitkat - Moto X 1st gen. (another one)
Google Play Services v7.5.74 (XXXXXX-038) with Android 4.4.2 Kitkat - Huawei Ascend P7

Notice the Google Play Services version. If ends with 438 succeeds, otherwise it fails.
# Update:

After some hours, its working now.
There are a delay o something when a device gets subscribed to a topic before it start getting notified?

Sorry :worried:

**Comment by RockoDev** [comment]
# Update 2:

Well, I'm still having issues with topic messaging...
1. Sometimes I'm not receiving topic notifications in some devices (randomly).
2. I NEVER receive topic notifications in Huawei devices. (see the device list below).

I've added more devices to the tests:

Success (usually):
Google Play Services v7.6.03 (1954927-446) with Android M - Nexus 9
Google Play Services v7.6.03 (1954927-438) with Android M - Nexus 5
Google Play Services v7.5.74 (1997312-430) with Android 5.1.1 Lollipop - Nexus 7
Google Play Services v7.5.74 (1997312-438) with Android 5.1.1 Lollipop - Nexus 5
Google Play Services v7.5.74 (1997312-438) with Android 5.0.2 Lollipop - OnePlus One
Google Play Services v7.5.74 (1997312-440) with Android 5.0.2 Lollipop - Galaxy S6 Edge
Google Play Services v7.5.74 (1997312-440) with Android 5.0.2 Lollipop - Galaxy S6 Edge (another one)
Google Play Services v7.5.74 (1997312-436) with Android 5.0.2 Lollipop - Moto G 1st gen.
Google Play Services v7.5.74 (1997312-436) with Android 5.0.2 Lollipop - Moto G 2nd gen.
Google Play Services v7.5.74 (1997312-436) with Android 4.4.4 Kitkat - Moto X 1st gen.
Google Play Services v7.5.74 (1997312-436) with Android 4.4.4 Kitkat - Moto X 1st gen. (another one)
Google Play Services v7.5.74 (1997312-034) with Android 4.2.2 Jelly Bean - ZTE Blade L2

Failed (always):
Google Play Services v7.5.74 (1997312-038) with Android 4.4.2 Kitkat - Huawei Ascend P7
Google Play Services v7.5.74 (1997312-036) with Android 4.3 Jelly Bean - Huawei Ascend G630

But if i send a notification to any device using the registration token, it works without issues.

**Comment by silvolu** [comment]
@rockodev could you please use [this form](https://support.google.com/code/contact/gcm_dev_support) to get direct support? Thanks!
