### ISSUE TITLE
com.google.android.gcm.demo I/GcmDemo﹕ registration failed.

### ISSUE THREAD

**Issue by ghost** [google/gcm#76]
Can anyone please help me solve the following error?

2161-12935/com.google.android.gcm.demo I/GcmDemo﹕ registration failed.
    senderId:XXXXXXX518
    error: MISSING_INSTANCEID_SERVICE

**Comment by silvolu** [comment]
Tokens can't be generated, because only devices with Google Play are supported. Is that not your case?

https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID.html#ERROR_MISSING_INSTANCEID_SERVICE

**Comment by silvolu** [comment]
Closing this one for inactivity.
