### ISSUE TITLE
GCM through Proxy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gcm#8]
```

I am trying to work GCM through proxy . I don't find any way to give my proxy 
details in the GCM server docs . 

I tried to set the System.setProperty . But it is not working for me .

The only way i can able to work it by modifying the gcm-server .  [ Included 
proxy details in Post() method . ]

Thanks 
D.Murugesan
```

Original issue reported on code.google.com by `sweat.mu...@gmail.com` on 28 Aug 2012 at 10:03

**Comment by rakesh-eltropy** [comment]
We also need to send notifications via proxy server.Not sure how to do that using GCM.

**Comment by fijojosep** [comment]
I am still seeing that proxy is not implemented in GCM server .  Is this resolved now? I see this issue as closed. I would like to re-open if its not implemented.

**Comment by rakesh-eltropy** [comment]
I have used following library for proxy:

https://github.com/alexjlockwood/gcm

```
transport := &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
client := &http.Client{Transport: transport}
sender := &gcm.Sender{ApiKey: viper.GetString("pushNotification.gcmAPIKey"), Http:client}
```
