### ISSUE TITLE
GoogleCloudMessaging.send only send Bundle string values

### ISSUE THREAD

**Issue by henrik-lindqvist** [google/gcm#83]
When sending upstream messages with GoogleCloudMessaging.send(), the Bundle for the data sent to the app server, in the JSON "data" property, are only included if it's String values (Bundle.putString). This is a JSON payload it should at least also send double, boolean values aswell.

Since Android doesn't have Parcelable JSON object, it could be encoded using Bundle for object, and put<Float|Integer|Parcelable|String>ArrayList for array, putBoolean for boolean, put<Double|Float|Integer> for number and putString for string properties.

**Comment by silvolu** [comment]
Thanks for your feedback, we are currently not planning on supporting this.
