### ISSUE TITLE
RestClient uses the deprecated registration_ids message property

### ISSUE THREAD

**Issue by secondsun** [google/gcm#84]
The sender in the rest client uses "registration_ids" instead of "to" when sending a single message.  

In the [target section](https://developers.google.com/cloud-messaging/downstream) of the downstream doc this field is said to be deprecated for general use.

**Comment by secondsun** [comment]
Additionally, because the "to" field is unsupported the rest-client can't be used to send topic messages.

**Comment by kroikie** [comment]
registration_ids is not deprecated.

**Comment by secondsun** [comment]
@kroikie 

Then what does "Though for general purposes it is deprecated, you can use registration_ids as a target for multicast messages to more than one device (up to 1000)." mean on https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages?

**Comment by kroikie** [comment]
Thanks @secondsun for the heads up on that, these docs are misleading and should be clearer, but registration_ids is not deprecated.

**Comment by secondsun** [comment]
@kroikie Gotcha. Where is the issues page for docs?  I would like to file/track this bug there.

**Comment by silvolu** [comment]
@secondsun we have an internal issue open for this. In the future, if you want to send feedback about the docs you can use the **Send Feedback** button that you can find on the right of the docs' navigation bar.
GCM doesn't have a public issue tracker (this one is not meant to be for gcm product or docs, just for the content of this repo).
