### ISSUE TITLE
Priority isn't available

### ISSUE THREAD

**Issue by cnordvik** [google/gcm#88]
Any chance we can get an update so we can use the new fields like priority? https://developers.google.com/cloud-messaging/server-ref

**Comment by dominikkontner** [comment]
I wrote a new rest client for the new API. Maybe you want to take a look at it.
If you find bugs, please report them. I try to fix them within a few days.
https://github.com/dominikkontner/GCM

**Comment by cnordvik** [comment]
@dominikkontner Looks good but actually Google claims they will update this repo so I'll wait a few more days and see if something happens before giving up :-)
