### ISSUE TITLE
GCM for IOS: Bitcode

### ISSUE THREAD

**Issue by Ruud-cb** [google/gcm#91]
New Apple standards recommend apps to have Bitcode enabled, GCM doesn't support Bitcode yet. Updated pods today to GCM 1.0.3. Got error when building for IOS device or archive:

```
d: '/PathToApp/Pods/Google/Libraries/libGGLCloudMessaging.a(GGLContext+CloudMessaging.o)' 
does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), 
obtain an updated library from the vendor, or disable bitcode for this target. 
for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by silvolu** [comment]
@Ruud thanks for your feedback! We will add it in the next release.

**Comment by amyleecodes** [comment]
Seconding this, as we're now trying to ship iOS 9 versions of our apps since the GM SDK is available. GCM (and dependencies) are stopping us from uploading bitcode versions of apps.

**Comment by Ruud-cb** [comment]
Just a side question, will it prevent me from publishing new apps? e.g. rejection on app submission?

**Comment by silvolu** [comment]
According to [Apple](https://developer.apple.com/library/prerelease/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35-SW2), _"**For iOS apps, bitcode is the default, but optional**. If you provide bitcode, all apps and frameworks in the app bundle need to include bitcode. **For watchOS apps, bitcode is required.**"_ So unless you are submitting with watchOS, you should be fine.

**Comment by amyleecodes** [comment]
Definitely optional, but it's important to support. Being able to slim a giant app down in size is going to be a HUGE boost for downloads, and can be the difference between staying under the cellular limit and not.

**Comment by tapz** [comment]
When are new versions of the binaries coming out? I has been a month since this issues was created and still no new binaries. It's just one compiler flag.

**Comment by blixt** [comment]
This is still an issue:

> ld: '.../Pods/GoogleUtilities/Libraries/libGTM_NSData+zlib.a(GTMNSData+zlib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

This issue has been around for almost four months now. When is the next version coming out?

**Comment by mohitsharma0690** [comment]
It's not as simple as flipping a flag for us. Having said that we know this is a priority request and we are trying our best to get it in as soon as possible.

**Comment by anhletuan** [comment]
I have the same problem. This issue hasn't been fixed :(.

**Comment by domhof** [comment]
Same problem here! When is the next version coming out?

**Comment by coolnalu** [comment]
Just ran into this issue as well.

**Comment by fulldecent** [comment]
This issue is just a subset of the more important issue:

>  We need this to be open source or else there will frequently be late nights where our release is held hostage to Google fixing an issue

---

> Even with the best intentions, Google has clearly demonstrated that closed source software is incompatible with peace of mind for iOS software development.

**Comment by fulldecent** [comment]
FYI, for anyone that is up at 5am and is committed to shipping product before you go to bed, here is the "f*ck you, just make it work, I need to sleep" solution.

![screen shot 2015-12-20 at 3 23 40 am](https://cloud.githubusercontent.com/assets/382183/11917161/8fb50360-a6c9-11e5-9b32-2f0385aac3a1.png)

**Comment by danielmlozano** [comment]
HAHAHA that solution saved my ass. Thanks a lot!

**Comment by elloboblanco** [comment]
Thanks @fulldecent !

**Comment by philippeluickx** [comment]
+1

**Comment by JuanjoArreola** [comment]
It would be nice to support bitcode, just saying.

**Comment by gask** [comment]
GCM needs to support bitcode urgently.
It's an absurdity it's been like this for 6 months.

**Comment by asafam** [comment]
+1

**Comment by danieltamiosso** [comment]
Any news?

**Comment by silvolu** [comment]
So, our problem here is that we depend on changes to our toolchain that we don't directly control.
We should be quite near the end of the work that enables us compile with bitcode enabled, but I don't have any specific dates to share unfortunately.

**Comment by ericb** [comment]
@silvolu Thanks for the update. ~~Is there anything the community can do to help, or is this an internal toolchain?~~

edit: Oops, missed your clarification in the comment.

**Comment by kiroskirin** [comment]
Any update on bitcode error from /Pods/GoogleUtilities/Libraries/libGTM_NSData+zlib.a(GTMNSData+zlib.o) ?

**Comment by dincho** [comment]
AGRH! Google! YOU AGAIN!

**Comment by mikkokut** [comment]
+1

**Comment by smaspe** [comment]
+1. This `libGTM_NSData+zlib` is included in the `Google/Analytics` pod, which sucks.

**Comment by weirany** [comment]
+1

**Comment by waparty** [comment]
+1

**Comment by zdziczkowski** [comment]
+1

**Comment by davidalonso** [comment]
+1

**Comment by pitoneux** [comment]
Here we are, moving our code from Parse to Firebase, and we hit this... ARG! bitcode please ?! ( and what else are we going to hit.... grrr....)

**Comment by nagaho** [comment]
@smaspe You can use GoogleAnalytics instead Google/Analytics now.

**Comment by luhonghai** [comment]
+1

**Comment by aleksgapp** [comment]
+1

**Comment by LordParsley** [comment]
+1

**Comment by smaspe** [comment]
@nagaho yeah, I kind of saw that, but the doc is incomplete, the imports are different, I just didn't have the time to figure this mess, and there are other libraries that have the issue anyway.

**Comment by bradenkeith** [comment]
+1

**Comment by yoller** [comment]
+1 :)

**Comment by domhof** [comment]
+1

**Comment by coryhymel** [comment]
+1

**Comment by derjohng** [comment]
+1 :(

**Comment by santilorenzo** [comment]
+1 I can't send my app with its Apple Watch extension target if I dasble the bitcode.

**Comment by naeem** [comment]
+1

**Comment by CisSovereign** [comment]
+1 Still an issue. May not use this going forward because of this issue.

**Comment by mohitsharma0690** [comment]
We're very close to adding Bitcode in GCM and will most likely release a new lib version with it in a week or so. We're also actively working on enabling Bitcode in all of GCM's internal deps but that might take a bit more time another week or so. 

Rest assured this is one of the priorities and we're very close to having this shipped with full bitcode support.

**Comment by ghost** [comment]
+1

**Comment by oussamaFirespotter** [comment]
+1

**Comment by mauropiccini** [comment]
+1

**Comment by DenisDorokhov** [comment]
+1

**Comment by pronebird** [comment]
`GoogleAnalytics` is very different from `Google/Analytics` and seem to be missing some headers and files.

**Comment by afshin-hoseini** [comment]
@fulldecent +1

**Comment by amit-bst** [comment]
+1

**Comment by mt404** [comment]
+1

**Comment by mertnesvat** [comment]
+1

**Comment by nikolajerry1993** [comment]
+1

**Comment by iantheparker** [comment]
+1

**Comment by brainloops** [comment]
+1

**Comment by Ruud-cb** [comment]
All those +1 almost feels like spam, any updates @silvolu ?

**Comment by silvolu** [comment]
@Ruud-cb sorry, work still in progress. We're near, but still cannot give you a timeframe I'm 100% confident about.

**Comment by Ruud-cb** [comment]
@silvolu Alright thanks for the update! A 50% - 99% estimate is welcome :). Are we talking about weeks, months.. years? Of course the earliest the best for everyone, but personally I would like to know if I can expect this to be "bitecode friendly" in the next 2 - 4 months.

**Comment by aried3r** [comment]
If the +1s keep coming, could this issue be locked and regularly be
updated? I'd much rather have updates, even if negative, than constant
emails about +1s.

**Comment by silvolu** [comment]
@Ruud-cb a matter of weeks :)

**Comment by hjanuschka** [comment]
+1

**Comment by silvolu** [comment]
This should be fixed now.

**Comment by mt404** [comment]
Yes!

**Comment by silvolu** [comment]
And I spoke too soon, sorry. Almost there.

**Comment by mohitsharma0690** [comment]
Should be fixed now. Please reopen if you see any issues.

Also please test with the latest version.
