### ISSUE TITLE
Help Me not able to run ./gradlew run -Pargs="<message>"

### ISSUE THREAD

**Issue by Zakirsheik123** [google/gcm#93]
Hi i'm trying to implement Cloud Messaging for Android and i'm following this documentation "https://developers.google.com/cloud-messaging/android/start" and i'm stuck in 4th step " Run the sample" 
I also tried running the same command without "./" ant this is what i get for long time and then it terminates 
gradlew run -Pargs="<message>"
Downloading https://services.gradle.org/distributions/gradle-2.2.1-all.zip
..............................................................................................................................................................................................................................................
 please help me out on this

**Comment by silvolu** [comment]
@Zakirsheik123 thanks for reporting this. Could you file your issue in the https://github.com/googlesamples/google-services where the source code for that apps lives? Thanks!
