### ISSUE TITLE
Neither old or new registration id is canonical

### ISSUE THREAD

**Issue by vishesh92** [google/gcm#94]
I have two registration ids in database one from the old version which used gcm.register() and the new one using instanceID.getToken

I sent a ghost notification to both of the registration ids which are of the same device. This is what I get. Old registration id (before app update generated using gcm.register)

`{
"multicast_id": 0000000,
"success": 1,
"failure": 0,
"canonical_ids": 0,
"results": [
    {
    "message_id": "0:1f9fd7ecd"
    }]
}`
New Registration id (After app update, generated using instanceID.getToken):

`{
"multicast_id": 0000000,
"success": 1,
"failure": 0,
"canonical_ids": 0,
"results": [
    {
    "message_id": "0:8ccf9fd7ecd"
    }]
}`
How can I remove or update the old registration ID? Please Help! Right now, I can't send notifications because of this. Since it will send double/duplicate notifications.

**Comment by silvolu** [comment]
Sorry about that, we are working on a fix. We will update this ticket after the fix is published.

**Comment by vishesh92** [comment]
Any updates?

**Comment by kroikie** [comment]
Still working on a fix, will update issue once fix is published.

**Comment by kroikie** [comment]
This should be fixed now, if a client uses the old register to retrieve an identifier then uses the new getToken. Using the old identifier should return the new identifier as the canonical ID.

**Comment by henrik-lindqvist** [comment]
Was this fixed locally in the jar, or do we need to check version of the installed Google Play Services? If so, in which version?

**Comment by costinm** [comment]
Fixed on the server.

**Comment by rams329** [comment]
How long the old registration id available on the server side ? 

I read the below one in google documentation -

"If you try to send a message using an old registration token, GCM will process the request as usual, but it will include the canonical ID in the registration_id field of the response. Make sure to replace the registration token stored in your server with this canonical ID, as eventually the old registration token will stop working."

For example if the server sends a notification to device after 30-60 days, will the old registration id still be available and process the request, and server returns the canonical id to server who sent notifications ?
