### ISSUE TITLE
CCS Documentation

### ISSUE THREAD

**Issue by awenger** [google/gcm#95]
Regarding the CCS XMPP documentation on [1]

```
<stream:stream to="gcm.googleapis.com"
        version="1.0" xmlns="jabber:client"
        xmlns:stream="http://etherx.jabber.org/streams"/>
```

should be:

```
<stream:stream to="gcm.googleapis.com"
        version="1.0" xmlns="jabber:client"
        xmlns:stream="http://etherx.jabber.org/streams">
```

(note the removed "/" at the end)

Took me quite some time to figure out why my connection was closed immediately.

Here is also a nice summary how to connect manually [2]

[1] https://developers.google.com/cloud-messaging/ccs
[2] https://groups.google.com/d/msg/android-gcm/hV80kHsROk8/5pHqtWaX7wwJ

**Comment by henrik-lindqvist** [comment]
The CCS documentation are missing much of the minimum requirements for the XMPP protocol, like binding (IQ) and session parts. This wrongfully gives the impression that it's easy to implement, it is not. I also started with just the CCS documentation, but ended up implementing a complete XMPP client, no small task.

**Comment by kroikie** [comment]
The docs have been updated to remove unnecessary slash.

I totally agree that implementing XMPP client is no small task. Work is underway to provide developers with an easier way to interact with CCS.
